### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by jcrben** [FingerArt/ApiDebugger#1]
This is a pretty cool project, but it lacks documentation and I had a bit of trouble even finding out how to use it! 

![image](https://cloud.githubusercontent.com/assets/5614134/21951897/cb1fedba-d9c3-11e6-8244-db3ed6b12eef.png)

Even a simple screenshot like this would help a lot.

**Comment by fingerart** [comment]
@jcrben sorry, because I have been busy recently, so did not write clearly, you can look at here [http://fingerart.me/2016/10/24/IntelliJ-IDEA-%E6%8F%92%E4%BB%B6ApiDebugger-v1-0-0/](http://fingerart.me/2016/10/24/IntelliJ-IDEA-%E6%8F%92%E4%BB%B6ApiDebugger-v1-0-0/)
