### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by bogdandynamic** [FingerArt/ApiDebugger#3]
Hi. Very useful plugin that I'm using for a while now. I recently encountered a problem when working with https URLs. The error is:

`sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

I'm using a development CA, with a root certificate, an intermediate one (signed by the root), and final certificates for every website/webapp (signed by the intermediate certificate). I imported all certificates using keytool but the error remains the same.

OS: OSX 10.13 
JAVA: 1.8.0.144

Can you provide some feedback or a workaround to the problem ?
Thanks.

**Comment by fingerart** [comment]
@bogdandynamic Thanks for you feedback on this issue. I'm going to release a new version for your problem, and I hope you'll keep your eyes on it.

**Comment by bogdandynamic** [comment]
Be sure I'll keep my eyes on it. It's a very helpful plugin and I don't have to use external apps like Postman to do the job.

**Comment by fingerart** [comment]
I an so sorry. I work very busy recently, Just taking a little free time added support for HTTPS, Currently, the plugin update is pending JetBrains approval. But, also cannot custom certificate, if you still can't meet your need, I can again this weekend update a version for you.

**Comment by bogdandynamic** [comment]
Hello. First of all I thank you for trying to fix the issue in your free
time. After the new version is available I'll update and test it.
Afterwards I'll give you related feedback.
